{% set name = "libsemigroups" %}
{% set version = "0.3.1" %}
{% set sha256 = "ebbdd098d3b9c08bfecf9de2e3bc1bb69f3fe68e0a56e9f25e51b026c93769c8" %}
{% set repo = "https://github.com/james-d-mitchell/libsemigroups" %}
{% set home = "https://james-d-mitchell.github.io/libsemigroups/" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: {{ repo }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  #git_rev: v{{ version }}
  #git_url: {{ repo }}.git
  #git_tag: autotools

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - toolchain

test:
  commands:
    - test -d ${PREFIX}/include/libsemigroups  # [unix]
    - test -f ${PREFIX}/include/libsemigroups/semigroups.h  # [unix]
    - test -f $PREFIX/lib/libsemigroups.dylib  # [osx]
    - test -f $PREFIX/lib/libsemigroups.so     # [linux]
    - test -f $PREFIX/lib/libsemigroups.a  # [unix]

    - if exist %LIBRARY_PREFIX%\include\libsemigroups\semigroups.h (exit 0) else (exit 1)  # [win]

about:
  home: {{ home }}
  license: GPL-3.0
  license_file: LICENSE 
  summary: 'C++ library for semigroups and monoids'

  description: |
    libsemigroups is a C++ library for semigroups and monoids; it is partly based on 
    [Algorithms for computing finite semigroups](https://www.irif.fr/~jep/PDF/Rio.pdf), 
    [Expository Slides](https://www.irif.fr/~jep/PDF/Exposes/StAndrews.pdf), and 
    [Semigroupe 2.01](https://www.irif.fr/~jep/Logiciels/Semigroupe2.0/semigroupe2.html) by Jean-Eric Pin.
  doc_url: {{ home }}
  dev_url: {{ repo }}

extra:
  recipe-maintainers:
    - james-d-mitchell
    - nthiery
