travis:
  secure:
    BINSTAR_TOKEN: WjsbFpIO6Vnrm1zXLbUNMs5+r8Jm/v+Ktn1nL540IVctOdwyNfyqdZYiis1uZmRfS2LzpCw2LOJQi3accw88TKWpDsEnp2+X7UeJ8gGaZ0htmNEGZ91wWhD0To2hwd3rffbT0Uk9xc9Ln6ucIENR/QGdrlJcEMP+XRbluDKj9WYWCmtL75bZSXqaYWTu3cABNLHJkoSYydz6gbAPewKJ01SF8N5KqeJIhgg7UyPaXNTrTY9HOgdaQfZEYlBcO9lVLCrtLy38i4L93S6DqewrxnCES5AXTUazBoo9343FrK7BnF1jwBCXLxe/hOIhAxNwj7VtXEK6vxuw7E6/otuihQ1rz6XU+9tdbcZaa6RJop5jfGbBZx5tvAGQs66rfh/wa2wMk2nHjV+1m0ayLN178DWObFBRl0yn/gdljTx6X21kGKjzkSUws/4/Ut2J5VS8i2vzhbFyLTLGNQhAoGrQ1qxGen1tQAAcYYPAiEE+aXRrlG4FAY1Zqeiiq9FDfEENjfhlmjdpLDttEDBoXxKHXkVfJ34FlBu1M9rlU4qv0seTtgmC38Suzt62PiR6zLISQizq8grboUU0Sf2CoqswASJ0VTNBKnIpS15xCSWriEVSYoZf94NMhCHggzpFR6oUGobtLgOQOshHuGEpoe7IxvW5oE9GagK47it6CfNLVP8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
