travis:
  secure:
    BINSTAR_TOKEN: KgKgnSEaeDFF8/1ymg6CEGKB46vZXm+lC7Zy7sWAjlfy7KpJ+l3bnrLCHthQ8Loksdd1juy/QJB9oqQQ34dO3auRygijUmIYlFbozHjNYuX1A/D6beoc5mdzcqO4w7mMSTOxUrk7MLspP3Mdse7FuNN3qM9CvQIKCo67iqzZzz59GiuY3NstgWTlXzRrqCrEcPLlc5VVKvo+7kWSrNOcA72/XFVHmge2ezM3J7KAU5ursDArH1YNab6JrnbQ4osC+kurD1NuNL70ytdfmk6si+Oee0LwA7kAHsbZICcbQblii1wNmVnHK3In05IsRiYTsWKsEa9DjKVxA9UliskAqxdotva3Bqpo7oZCso+Rw49UH4/J6EAH8XEGbw+ARdxM1CB1DZtH4/0rJSSCHWCcB3/JPA2wjB98J+gCeBtE2f3YP/qcuCyFhhheVQN/53v0OElT/rR4MVpMd5VZWQEW5a7f08SzSO25Jc/yeX0cRWarR4hdUVQAL8nUI0CFG85evxjTyjhNpcWXVXFA/YryHKa83dWRDC731jMoOHD8jxY5SDAqZk3Lu/IIzLCAmKU7NzpcxVKyeIorO0ZcE9tSjZoSxOJYLAiiVApzmUj+/lkyZUlHFaizjB7myTa6GqX1vrsX3pt+x//5nneQ8V9FQJREjMa10FztF9ZWmaN7Hxs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
